services:
  mitigation_manager:
    container_name: resilmesh_sop_mm
    hostname: resilmesh_sop_mm
    build:
      context: .
    expose:
      - ${MM_PORT:-8002}
    networks:
      resilmesh:
networks:
  resilmesh:
    external: true
    name: resilmesh_network
