services:
  resilmesh-sop-mm:
    container_name: resilmesh-sop-mm
    build:
      context: .
    expose:
      - ${MM_PORT:-8002}
    networks:
      resilmesh:
networks:
  resilmesh:
    external: true
    name: resilmesh_network
